//! The inventory of observed text, configuration and string-resource
//! dialects (stage F12-A).
//!
//! One row per dialect: which surveyed installation members carry it, the
//! line terminator and encoding they were observed with, the lexical
//! features the survey found, how far its grammar is established and which
//! reader (if any) this crate has for it. The survey and every value here
//! are recorded in
//! `docs/findings/2026-09-28-f12-a-text-dialects-and-lossless-config-nodes.md`.
//!
//! A member is routed to a dialect by the observed member rule
//! ([`dialect_for_member`]), never by an extension alone (spec F12,
//! non-negotiable #1: do not assume INI/CSV/JSON because a filename
//! resembles one). A member no rule covers has no dialect.

use cs_types::evidence::ClaimStatus;

use crate::text::lines::LineTerminator;

/// The archive the surveyed configuration members live in.
pub const CRIMSON_ROF: &str = "GOSDATA/ASSETS/crimson.rof";

/// One observed text or resource dialect.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum TextDialect {
    /// `[SECTION]` headers, whole-line `;` comments and
    /// `KEY=field,field,…` entries with double-quoted fields
    /// (`LAYOUT.CSV`, `SCRAPBOOK.CSV`). Read by
    /// [`crate::text::keyed_list::read_keyed_list`].
    KeyedList,
    /// The `.SCRIPT` UI script language (`main { gui_create { … } }`
    /// blocks, typed locals, `callback(…)` calls). A script language, not
    /// configuration: its inventory belongs to F13.
    UiScript,
    /// C preprocessor resource-id headers (`#define NAME value`, `//`
    /// comments) generated by Microsoft Developer Studio.
    ResourceHeader,
    /// `name = SYMBOL` lines mapping readable script identifiers to the
    /// obfuscated names used in the `.SCRIPT` members (`DEBUGINFO.TXT`).
    SymbolMap,
    /// Win32 PE images whose resource sections carry localizable strings
    /// and UI resources (`strings.dll`, `language.dll`, `langui.dll`). Read
    /// as inert data only, never loaded (spec F12).
    PeResources,
    /// Rich Text Format documents shipped next to the executable
    /// (`Readme.rtf`, `EULA.RTF`).
    RichText,
}

impl TextDialect {
    /// Every dialect, in inventory order.
    pub const ALL: [Self; 6] = [
        Self::KeyedList,
        Self::UiScript,
        Self::ResourceHeader,
        Self::SymbolMap,
        Self::PeResources,
        Self::RichText,
    ];

    /// Stable label.
    pub const fn code(self) -> &'static str {
        match self {
            Self::KeyedList => "text.keyed_list",
            Self::UiScript => "text.ui_script",
            Self::ResourceHeader => "text.resource_header",
            Self::SymbolMap => "text.symbol_map",
            Self::PeResources => "pe.resources",
            Self::RichText => "text.rtf",
        }
    }

    /// The dialect's inventory row.
    pub fn record(self) -> &'static DialectRecord {
        TEXT_DIALECT_INVENTORY
            .iter()
            .find(|record| record.dialect == self)
            .expect("every dialect has one inventory row")
    }
}

/// Which installation members a dialect was observed in.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum MemberRule {
    /// One archive member, by its path inside the container.
    Member {
        /// Container path relative to the installation root.
        container: &'static str,
        /// Member path inside the container.
        member: &'static str,
        /// Decoded length observed in the survey.
        length: u64,
    },
    /// Every member of one archive directory with one suffix; the survey
    /// read all of them.
    Directory {
        /// Container path relative to the installation root.
        container: &'static str,
        /// Member directory, `/`-terminated.
        directory: &'static str,
        /// Member name suffix.
        suffix: &'static str,
        /// How many members the survey found.
        count: u32,
    },
    /// A loose installation file.
    Loose {
        /// Path relative to the installation root.
        path: &'static str,
        /// Length observed in the survey.
        length: u64,
    },
}

impl MemberRule {
    /// Whether the rule covers `member` of `container` (`member` is `None`
    /// for a loose file). Paths compare ASCII case-insensitively, the way
    /// installation paths are keyed (`RelativePath::logical_key`).
    pub fn matches(&self, container: &str, member: Option<&str>) -> bool {
        match (*self, member) {
            (
                Self::Member {
                    container: expected,
                    member: name,
                    ..
                },
                Some(member),
            ) => container.eq_ignore_ascii_case(expected) && member.eq_ignore_ascii_case(name),
            (
                Self::Directory {
                    container: expected,
                    directory,
                    suffix,
                    ..
                },
                Some(member),
            ) => {
                container.eq_ignore_ascii_case(expected)
                    && member.len() > directory.len() + suffix.len()
                    && member.is_char_boundary(directory.len())
                    && member[..directory.len()].eq_ignore_ascii_case(directory)
                    && !member[directory.len()..].contains('/')
                    && member.is_char_boundary(member.len() - suffix.len())
                    && member[member.len() - suffix.len()..].eq_ignore_ascii_case(suffix)
            }
            (Self::Loose { path, .. }, None) => container.eq_ignore_ascii_case(path),
            _ => false,
        }
    }
}

/// The byte encoding a dialect was observed with.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ObservedEncoding {
    /// Every surveyed byte is 7-bit ASCII. The code page a localized
    /// installation uses for bytes above `0x7F` is unknown, so readers keep
    /// names and values as bytes.
    Ascii,
    /// A binary container; its strings carry their own encoding.
    Binary,
}

/// A lexical feature the survey observed in a dialect's members.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LexicalFeature {
    /// `[name]` section header lines, some indented with tabs or spaces.
    SectionHeaders,
    /// `;` as the first non-blank byte of a line.
    SemicolonLineComments,
    /// `//` line comments.
    SlashLineComments,
    /// Blank lines.
    BlankLines,
    /// `key=value`, with spaces or tabs between key and `=` in some lines.
    KeyEqualsValue,
    /// `,`-separated fields, including empty ones.
    CommaFields,
    /// A field enclosed in `"` that contains `,`.
    QuotedFieldsWithCommas,
    /// `<NAME>` placeholders inside field values.
    AnglePlaceholders,
    /// `0x`-prefixed hexadecimal field values.
    HexValues,
    /// `#define NAME value` lines.
    Defines,
    /// Braced blocks and statements of a script language.
    ScriptBlocks,
    /// A NUL byte after the last line.
    TrailingNul,
}

/// How a dialect is read.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum DialectReader {
    /// [`crate::text::keyed_list::read_keyed_list`].
    KeyedList,
    /// No reader in this crate yet; `stage` is the spec stage that owns it.
    Deferred {
        /// The owning spec stage.
        stage: &'static str,
        /// Why it is not read here.
        reason: &'static str,
    },
}

/// One inventory row.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct DialectRecord {
    /// The dialect.
    pub dialect: TextDialect,
    /// The surveyed members that carry it.
    pub members: &'static [MemberRule],
    /// The line terminator every surveyed line ended with (the last line
    /// of a member excepted), or `None` for a binary container.
    pub terminator: Option<LineTerminator>,
    /// The observed encoding.
    pub encoding: ObservedEncoding,
    /// The observed lexical features.
    pub features: &'static [LexicalFeature],
    /// How far the grammar is established: at most `ObservedTool` (a
    /// survey of one English installation), `Documented` only for public
    /// formats.
    pub grammar: ClaimStatus,
    /// The reader, if any.
    pub reader: DialectReader,
    /// What is not known about the dialect.
    pub unknowns: &'static [&'static str],
}

/// The dialect inventory, one row per [`TextDialect`].
pub static TEXT_DIALECT_INVENTORY: [DialectRecord; 6] = [
    DialectRecord {
        dialect: TextDialect::KeyedList,
        members: &[
            MemberRule::Member {
                container: CRIMSON_ROF,
                member: "ASSETS/LAYOUT.CSV",
                length: 56_148,
            },
            MemberRule::Member {
                container: CRIMSON_ROF,
                member: "ASSETS/SCRAPBOOK.CSV",
                length: 35_154,
            },
        ],
        terminator: Some(LineTerminator::CrLf),
        encoding: ObservedEncoding::Ascii,
        features: &[
            LexicalFeature::SectionHeaders,
            LexicalFeature::SemicolonLineComments,
            LexicalFeature::BlankLines,
            LexicalFeature::KeyEqualsValue,
            LexicalFeature::CommaFields,
            LexicalFeature::QuotedFieldsWithCommas,
            LexicalFeature::AnglePlaceholders,
            LexicalFeature::HexValues,
        ],
        grammar: ClaimStatus::ObservedTool,
        reader: DialectReader::KeyedList,
        unknowns: &[
            "whether a ';' after a value starts a comment (never observed)",
            "whether values or fields are trimmed of blank bytes",
            "escaped or embedded quotes (never observed)",
            "whether indentation of sections and entries is significant",
            "how a line starting with ':' (one in LAYOUT.CSV) is read",
            "field types, units and the meaning of <NAME> placeholders",
            "the code page of bytes above 0x7F in localized installations",
        ],
    },
    DialectRecord {
        dialect: TextDialect::UiScript,
        members: &[MemberRule::Directory {
            container: CRIMSON_ROF,
            directory: "ASSETS/SCRIPTS/",
            suffix: ".SCRIPT",
            count: 61,
        }],
        terminator: Some(LineTerminator::CrLf),
        encoding: ObservedEncoding::Ascii,
        features: &[LexicalFeature::ScriptBlocks],
        grammar: ClaimStatus::Unknown,
        reader: DialectReader::Deferred {
            stage: "F13-A",
            reason: "a script language with calls and control flow, not configuration",
        },
        unknowns: &["the whole grammar and every callback id"],
    },
    DialectRecord {
        dialect: TextDialect::ResourceHeader,
        members: &[
            MemberRule::Member {
                container: CRIMSON_ROF,
                member: "ASSETS/SCRIPTS/RESOURCE.H",
                length: 29_579,
            },
            MemberRule::Member {
                container: CRIMSON_ROF,
                member: "ASSETS/SCRIPTS/RESRC1.H",
                length: 8_922,
            },
        ],
        terminator: Some(LineTerminator::CrLf),
        encoding: ObservedEncoding::Ascii,
        features: &[
            LexicalFeature::SlashLineComments,
            LexicalFeature::BlankLines,
            LexicalFeature::Defines,
        ],
        grammar: ClaimStatus::ObservedTool,
        reader: DialectReader::Deferred {
            stage: "F12-B",
            reason: "the header-to-resource id mapping needs the PE resource reader",
        },
        unknowns: &[
            "whether the shipped game reads these headers at run time",
            "which PE image each header describes beyond its own comment",
        ],
    },
    DialectRecord {
        dialect: TextDialect::SymbolMap,
        members: &[MemberRule::Member {
            container: CRIMSON_ROF,
            member: "ASSETS/SCRIPTS/DEBUGINFO.TXT",
            length: 20_505,
        }],
        terminator: Some(LineTerminator::Lf),
        encoding: ObservedEncoding::Ascii,
        features: &[LexicalFeature::KeyEqualsValue, LexicalFeature::TrailingNul],
        grammar: ClaimStatus::ObservedTool,
        reader: DialectReader::Deferred {
            stage: "F13-A",
            reason: "it names script symbols; its consumer is the script inventory",
        },
        unknowns: &[
            "whether the shipped game reads it",
            "which scripts each symbol belongs to",
        ],
    },
    DialectRecord {
        dialect: TextDialect::PeResources,
        members: &[
            MemberRule::Loose {
                path: "strings.dll",
                length: 131_072,
            },
            MemberRule::Loose {
                path: "GOSDATA/ASSETS/BINARIES/language.dll",
                length: 32_768,
            },
            MemberRule::Loose {
                path: "GOSDATA/ASSETS/BINARIES/langui.dll",
                length: 282_624,
            },
        ],
        terminator: None,
        encoding: ObservedEncoding::Binary,
        features: &[],
        grammar: ClaimStatus::Documented,
        reader: DialectReader::Deferred {
            stage: "F12-B",
            reason: "the bounded, cycle-checked resource directory reader",
        },
        unknowns: &[
            "which resource types, ids and languages each image carries",
            "the code pages of their string tables",
        ],
    },
    DialectRecord {
        dialect: TextDialect::RichText,
        members: &[
            MemberRule::Loose {
                path: "Readme.rtf",
                length: 57_539,
            },
            MemberRule::Loose {
                path: "EULA.RTF",
                length: 266_123,
            },
        ],
        terminator: None,
        encoding: ObservedEncoding::Ascii,
        features: &[],
        grammar: ClaimStatus::Documented,
        reader: DialectReader::Deferred {
            stage: "none",
            reason: "installer documents; no game consumer is known",
        },
        unknowns: &["whether the game or its launcher displays them"],
    },
];

/// The dialect a surveyed member was observed with, or `None` for a member
/// no rule covers (whatever its extension). `member` is `None` for a loose
/// file, whose installation path is then `container`.
pub fn dialect_for_member(container: &str, member: Option<&str>) -> Option<TextDialect> {
    TEXT_DIALECT_INVENTORY
        .iter()
        .find(|record| {
            record
                .members
                .iter()
                .any(|rule| rule.matches(container, member))
        })
        .map(|record| record.dialect)
}
