//! Evidence-report harness for task F12-J, reissued by Rally #1174
//! `EVIDENCE-CONTENT-DIGEST-OUTLIERS-REPAIR` (owner decision of 2026-10-10:
//! option (a)).
//!
//! F12-J's committed report recorded a *task-scoped* digest — SHA-256 over the
//! concatenated 32-byte decoded digests of two members — in
//! `source.content_sha256`, whose contract meaning is the canonical
//! whole-installation content fingerprint (`schemas/evidence.schema.json`,
//! `docs/contracts/CLI-EVIDENCE.md`). Its writer was
//! `private/evidence/F12-J/harness.py`, which lived on the producing host and
//! no longer exists, so this harness is the report's first committed writer.
//! It follows the same #804 shape as `evidence/f05_d.rs`:
//!
//! * `source` comes from production discovery, so `content_sha256` is the
//!   canonical value every other committed report carries;
//! * `review.identity` is the original review's own text, byte-unchanged, and
//!   the regeneration facts are appended to `review.method` instead;
//! * the run facts are this run's own — including the artifacts, whose digests
//!   are fresh, because the originals embedded the producing host's
//!   installation path and cannot reproduce here;
//! * `unknowns` keeps its original single recorded issue: the task's
//!   acceptance *is* that it stays open, so this report is validated without
//!   `--require-pass`.
//!
//! Run it from the workspace root, exactly as:
//!
//! 0. ```sh
//!    cargo build -p cs_inspect --locked
//!    ```
//!    (the production `cs-inspect` binary the harness runs the artifact
//!    commands with; it fails loudly if the binary is missing)
//! 1. ```sh
//!    cargo test --workspace --locked -- accept_f12_j_ --include-ignored \
//!      2>&1 | tee private/evidence/F12-J/cargo-test.log
//!    ```
//!    (record the pipeline's exit status — it is `CS_EVIDENCE_EXIT_CODE`.)
//! 2. ```sh
//!    CS_EVIDENCE_DIR=private/evidence/F12-J \
//!    CS_CANDIDATE_TREE=$(git rev-parse 'HEAD^{tree}') \
//!    CS_EVIDENCE_ARGV="cargo test --workspace --locked -- accept_f12_j_ --include-ignored" \
//!    CS_EVIDENCE_EXIT_CODE=<status from step 1> \
//!      cargo test --locked --test campaign evidence_report_f12_j -- --ignored
//!    ```
//! 3. ```sh
//!    python3 tools/validate_evidence.py private/evidence/F12-J/acceptance.json \
//!      --artifact-root private/evidence/F12-J
//!    ```
//!    (no `--require-pass`: the recorded unknown above must stay recorded.)
//! 4. Commit a copy of `acceptance.json` as `docs/findings/evidence/F12-J.json`.

use super::*;

/// The container the two member reads take, as the installation spells it.
const CRIMSON_ROF: &str = "GOSDATA/ASSETS/crimson.rof";

/// The `accept_f12_j_` tests, in the full spelling their original report
/// recorded, each with the evidence entries that row cites. The original
/// report recorded two rows; the third test exists today and is this run's
/// own. Statuses come from the recorded log.
const ASSERTIONS: &[(&str, &[&str])] = &[
    (
        "config::tests::accept_f12_j_a_misspelt_colour_is_retained_unconverted",
        &[
            "cargo-test.log",
            "an authored T record spelling `oxff1E283C` at the documented Color position: \
             FieldSpelling::Text under FieldKind::Color, NotANumber for a 32-bit and a float \
             width, the record retained and byte-exact reassembly; a well-formed 0x control \
             converts",
        ],
    ),
    (
        "config::tests::accept_f12_j_misspelt_colour_parses_to_zero_and_renders_near_black",
        &["cargo-test.log"],
    ),
    (
        "config::tests::accept_f12_j_retail_misspelt_colour_fields_stay_raw",
        &[
            "cargo-test.log",
            "rof-read-layout.json",
            "rof-read-scrapbookzoom.json",
            "the three SBZ_T_*J entries of [@ScrapbookZoom@] at member lines 1156-1158 carry \
             `oxff1E283C` verbatim at field 7 and are refused as NotANumber; SBZ_T_CAPTIONA's \
             `xff000000` (line 1121) is refused the same way; all 26 slot letters exist; the \
             decoded member's digest is \
             b50ea48bbe97ea098d76575115629bfbe6d0f55165fa364c939f9fb089892583",
        ],
    ),
];

/// The original report's `review.method`, byte for byte. The regeneration
/// facts are appended to it, never substituted for it.
const ORIGINAL_METHOD: &str = "Generated by private/evidence/F12-J/harness.py from real runs on the candidate tree recorded in `candidate_tree`, not written by hand; the harness refuses to write unless both expected accept_f12_j_ tests ran and passed. content_sha256 is SHA-256 over the concatenated 32-byte decoded digests of ASSETS/LAYOUT.CSV and ASSETS/SCRIPTS/SCRAPBOOKZOOM.SCRIPT. The reviewer independently re-derived every load-bearing claim with its own readers, outside the production parsers: the retail member carries `oxff1E283C` verbatim at lines 1156-1158 and `xff000000` at line 1121 of [@ScrapbookZoom@], with 26 SBZ_T_TITLEA-Z records; SCRAPBOOKZOOM.SCRIPT writes only `szid` (YC) and `nresid` (DI) on the three text objects and never goscolor (DEBUGINFO.TXT: goscolor=$$OJ$$, szid=YC, nresid=DI, ntitleresid/ncaptionresid/ntextresid=ATA/BTA/CTA); crimson.exe (344851 bytes) imports no MSVCRT; crimson.icd (2580578 bytes) .text blocks measure 7.34-7.96 bits/byte of entropy per 64 KiB, .rdata is intact and carries no layout-parser strings; MSVCRT imports include sscanf, fscanf, strtol, atol, atoi, strtod, atof and not strtoul; no other installed PE carries layout strings or numeric-parse imports. The reviewer fixed one defect: the finding claimed the script assigns geometry/position to the text objects, but the script writes only name and resource id — the layout supplies position as well as colour. Deliberately not --require-pass: the task's acceptance is that this rule stays a recorded unresolved issue.";

/// What this reissue adds to `review.method`: what changed, why the artifact
/// digests are fresh and which selection the run recorded.
const REGENERATION: &str = "Regeneration for Rally #1174 (EVIDENCE-CONTENT-DIGEST-OUTLIERS-REPAIR) on 2026-10-10 by bunny-2/bunny-2: the report was reissued by the committed harness crates/cs_app/tests/campaign/evidence/f12_j.rs, run through the four-step sequence in its module doc, because the sentence above recorded a task-scoped digest in source.content_sha256 — a field whose contract meaning is the canonical whole-installation content fingerprint. source.content_sha256 is now cs_assets::install::content_fingerprint over the manifest production discovery reads (a0223506e512b50c0e0445ba73204a0461e60197e28d58a7f7144632d262c12d), the value every other committed report carries; the two-member scoped value the sentence above describes (89228009451e1841ecf352bc83f1a7ea5a68d51717a04d10d52007c64fd6e502) still re-derives from the same installation bytes through production code in accept_evidence_content_digest_outliers_each_documented_scoped_digest_still_re_derives, and docs/findings/2026-10-10-evidence-content-digest-outliers.md holds the measurement. review.identity above is byte-unchanged: the implementer and reviewer facts stand exactly as the original review wrote them, and this regeneration is recorded here instead of in the identity (#804 convention). Run facts are this run's own: candidate_tree, created_at, command.cwd, the test counts, the assertion statuses and the artifact digests come from the sequence above rather than being carried over. The artifact digests are fresh, not the original report's: inventory.json, rof-read-layout.json and rof-read-scrapbookzoom.json each carry this installation's host_root, the original run recorded another host's, so equivalent content on this host hashes differently — the layout read here reproduces d64f5b2320783966cce600ba13e5aef407ee2fac92a704baf351eca74ae959f4, the digest the T351 report records for the same production command, and inventory.json and rof-read-scrapbookzoom.json are measured on this run. The selection found three accept_f12_j_ tests where the original report recorded two, because the third test exists today: the counts and the assertion rows above are this run's own. The recorded unknown above stays open and unchanged, so this report is validated without --require-pass, as the method above says. The claim stays implemented: a merge awards checked, never verified_original, and nothing here observes the original game running. `candidate_tree` is the tree of the commit the suite and this harness ran on; the branch can be rebased onto a later main after that run, so it names the tree that was tested rather than necessarily the merged one, and the sentinel tests read this report's committed copy under docs/findings/evidence/ only for its source fingerprints.";

/// The single unknown the original report recorded, unchanged: it names the
/// affected content and its resolving task, and this task does not close it.
const UNKNOWNS: [&str; 1] = [
    "What the original's layout reader does with a colour field spelled without a `0x` prefix (`oxff1E283C` on the SBZ_T_TITLEJ/CAPTIONJ/TEXTJ records, `xff000000` on SBZ_T_CAPTIONA — all in [@ScrapbookZoom@], all live). The reader is code inside the SafeDisc-encrypted .text of crimson.icd (per-block entropy 7.3-8.0, entry point not code); the readable import table bounds the CRT candidates to sscanf, fscanf, strtol, atol, atoi, strtod, atof (strtoul is not imported) but no call site is observable. Resolution needs an owner original-run capture of the J zoom page's rendered colour, or unpacking the engine image (the task #351 lead) followed by a code reading; the configuration verification stage is F12-D.",
];

/// The original review's identity, byte for byte: the regeneration must never
/// rewrite who implemented or reviewed this report.
fn review_identity() -> String {
    "implementer: devin-1 (SWE-2), which submitted #376; reviewed and regenerated by devin-1 (SWE-2), the Rally-assigned reviewing agent for #376, in a separate session with a fresh context. The actor identity is the same as the implementer's, so per AGENTS.md this is not independent evidence: the merge awards `checked`, never `verified_original` or `release_approved`.".to_owned()
}

/// Evidence-report harness for task F12-J (Rally #376), reissued under #1174.
/// It refuses every missing input: a report written from a partial sequence
/// would be worse than no report at all.
#[test]
#[ignore = "evidence harness: needs CS_EVIDENCE_DIR, CS_CANDIDATE_TREE, CS_EVIDENCE_ARGV, CS_EVIDENCE_EXIT_CODE, CS_GAME_DIR"]
fn evidence_report_f12_j_writes_the_acceptance_report() {
    let evidence_dir = workspace_path(&env_var("CS_EVIDENCE_DIR"));
    fs::create_dir_all(&evidence_dir)
        .unwrap_or_else(|error| panic!("create {}: {error}", evidence_dir.display()));
    let candidate_tree = env_var("CS_CANDIDATE_TREE");
    let argv: Vec<String> = env_var("CS_EVIDENCE_ARGV")
        .split_whitespace()
        .map(str::to_owned)
        .collect();
    assert!(
        argv.iter().any(|arg| arg == "accept_f12_j_"),
        "CS_EVIDENCE_ARGV must be F12-J's own acceptance selection, got {argv:?}"
    );
    let exit_code: i32 = env_var("CS_EVIDENCE_EXIT_CODE")
        .parse()
        .expect("CS_EVIDENCE_EXIT_CODE must be the exit status of the acceptance run");
    let game_dir = PathBuf::from(env_var("CS_GAME_DIR"));

    let head_tree = git(&["rev-parse", "HEAD^{tree}"]);
    assert_eq!(
        candidate_tree, head_tree,
        "CS_CANDIDATE_TREE must be `git rev-parse 'HEAD^{{tree}}'` of the tested commit; \
         old reports cannot be reused for new code"
    );

    let log_path = evidence_dir.join("cargo-test.log");
    let log = fs::read_to_string(&log_path).unwrap_or_else(|error| {
        panic!(
            "cannot read the acceptance log {}: {error} (step 1 must tee its output there)",
            log_path.display()
        )
    });
    let suite = parse_f12_j_suite(&log);
    assert_eq!(
        suite.assertions.len(),
        ASSERTIONS.len(),
        "the log holds {} accept_f12_j_ tests and the report records {}: {:?}",
        suite.assertions.len(),
        ASSERTIONS.len(),
        suite.assertions
    );

    let found = discover(&game_dir)
        .expect("production discovery must read the original installation for the evidence record");
    let install_sha256 = fingerprint(&found.manifest).to_hex();
    let content_sha256 = content_fingerprint(&found.manifest).to_hex();

    // The inventory report: the production `cs-inspect inventory` command's
    // own bytes.
    let inventory_path = evidence_dir.join("inventory.json");
    let inventory_out = inventory_path.display().to_string();
    let cs_path = game_dir.display().to_string();
    run_cs_inspect(
        &cs_inspect_binary(),
        &[
            "inventory",
            "--cs-path",
            cs_path.as_str(),
            "--out",
            inventory_out.as_str(),
        ],
        &inventory_path,
        "inventory",
    );

    // The two member reads: the production `cs-inspect rof --member` reports.
    run_rof_read(
        &game_dir,
        "ASSETS/LAYOUT.CSV",
        &evidence_dir.join("rof-read-layout.json"),
    );
    run_rof_read(
        &game_dir,
        "ASSETS/SCRIPTS/SCRAPBOOKZOOM.SCRIPT",
        &evidence_dir.join("rof-read-scrapbookzoom.json"),
    );

    let artifacts = vec![
        artifact(&log_path, "log", &evidence_dir),
        artifact(&evidence_dir.join("inventory.json"), "json", &evidence_dir),
        artifact(
            &evidence_dir.join("rof-read-layout.json"),
            "json",
            &evidence_dir,
        ),
        artifact(
            &evidence_dir.join("rof-read-scrapbookzoom.json"),
            "json",
            &evidence_dir,
        ),
    ];

    let engine = Engine {
        rust: rustc_version(),
        bevy: locked_version("bevy"),
        avian: locked_version("avian3d"),
    };
    let unknowns: Vec<String> = UNKNOWNS
        .iter()
        .map(|unknown| (*unknown).to_owned())
        .collect();

    let method = format!("{ORIGINAL_METHOD} {REGENERATION}");
    let report = format!(
        "{{\n\
         \x20\"schema_version\": 1,\n\
         \x20\"task_id\": \"F12-J\",\n\
         \x20\"candidate_tree\": {},\n\
         \x20\"engine\": {},\n\
         \x20\"created_at\": {},\n\
         \x20\"command\": {{\"argv\": {}, \"cwd\": {}, \"exit_code\": {}}},\n\
         \x20\"source\": {{\"install_sha256\": {}, \"content_sha256\": {}}},\n\
         \x20\"seed\": 0,\n\
         \x20\"ticks\": {{\"start\": 0, \"end\": 0}},\n\
         \x20\"overrides\": [],\n\
         \x20\"capabilities\": [\"retail\", \"synthetic\"],\n\
         \x20\"tests\": {{\"discovered\": {}, \"executed\": {}, \"passed\": {}, \"failed\": {}, \"ignored\": {}}},\n\
         \x20\"assertions\": [{}],\n\
         \x20\"artifacts\": [{}],\n\
         \x20\"unknowns\": {},\n\
         \x20\"review\": {{\"identity\": {}, \"method\": {}}},\n\
         \x20\"claim\": \"implemented\"\n\
         }}\n",
        jstr(&candidate_tree),
        engine_json(&engine),
        jstr(&iso_utc_now()),
        str_array(&argv),
        jstr(&git(&["rev-parse", "--show-toplevel"])),
        exit_code,
        jstr(&install_sha256),
        jstr(&content_sha256),
        suite.discovered,
        suite.executed,
        suite.passed,
        suite.failed,
        suite.ignored,
        tabled_assertions(&log, ASSERTIONS),
        artifact_array(&artifacts),
        str_array(&unknowns),
        jstr(&review_identity()),
        jstr(&method),
    );

    let out = evidence_dir.join("acceptance.json");
    fs::write(&out, &report).unwrap_or_else(|error| panic!("write {}: {error}", out.display()));

    let written = fs::read_to_string(&out).expect("the report reads back");
    let content_line = format!("\"content_sha256\": \"{content_sha256}\"");
    for needle in [
        "\"schema_version\": 1",
        "\"task_id\": \"F12-J\"",
        "\"claim\": \"implemented\"",
        content_line.as_str(),
        "\"unknowns\": [",
        "\"artifacts\": [",
    ] {
        assert!(
            written.contains(needle),
            "the written report is missing {needle:?}:\n{written}"
        );
    }
    assert!(
        suite.failed == 0 && exit_code == 0,
        "the acceptance run failed (exit {exit_code}, {} failed): the report was written \
         honestly and must NOT validate; fix the tests first",
        suite.failed
    );
    println!("wrote {}", out.display());
}

/// [`parse_suite_prefixed`] with F12-J's own test prefix.
fn parse_f12_j_suite(log: &str) -> Suite {
    parse_suite_prefixed(log, "accept_f12_j_")
}

/// One `cs-inspect rof --member` run: the production command's own bytes,
/// one process per report, so the digest is what a standalone run writes.
fn run_rof_read(game_dir: &Path, member: &str, out: &Path) {
    let cs_path = game_dir.display().to_string();
    let out_path = out.display().to_string();
    let args = [
        "rof",
        "--cs-path",
        cs_path.as_str(),
        "--container",
        CRIMSON_ROF,
        "--member",
        member,
        "--out",
        out_path.as_str(),
    ];
    run_cs_inspect(
        &cs_inspect_binary(),
        &args,
        out,
        &format!("rof --member {member}"),
    );
}
