//! Evidence-report harness for task T351, reissued by Rally #1174
//! `EVIDENCE-CONTENT-DIGEST-OUTLIERS-REPAIR` (owner decision of 2026-10-10:
//! option (a)).
//!
//! T351's committed report recorded a *task-scoped* digest — SHA-256 over
//! `spelling stored-digest` lines for the 65 container members the stage read
//! — in `source.content_sha256`, whose contract meaning is the canonical
//! whole-installation content fingerprint (`schemas/evidence.schema.json`,
//! `docs/contracts/CLI-EVIDENCE.md`). Its writer was
//! `private/evidence/T351/harness.py`, which lived on the producing host and
//! no longer exists, so this harness is the report's first committed writer.
//! It follows the same #804 shape as `evidence/f05_d.rs`:
//!
//! * `source` comes from production discovery, so `content_sha256` is the
//!   canonical value every other committed report carries;
//! * `review.identity` is the original review's own text, byte-unchanged, and
//!   the regeneration facts are appended to `review.method` instead —
//!   including the correction that the scoped value was computed over the
//!   members' *stored* extent digests, not their decoded digests as the
//!   original method says;
//! * the run facts are this run's own; `rof-read-layout.json` reproduces the
//!   original report's artifact byte for byte;
//! * `unknowns` keeps its original nine recorded issues: the task's acceptance
//!   *is* that they stay open, so this report is validated without
//!   `--require-pass`.
//!
//! Run it from the workspace root, exactly as:
//!
//! 0. ```sh
//!    cargo build -p cs_inspect --locked
//!    ```
//!    (the production `cs-inspect` binary the harness runs the artifact
//!    commands with; it fails loudly if the binary is missing)
//! 1. ```sh
//!    cargo test --workspace --locked -- accept_t351_ --include-ignored \
//!      2>&1 | tee private/evidence/T351/cargo-test.log
//!    ```
//!    (record the pipeline's exit status — it is `CS_EVIDENCE_EXIT_CODE`.)
//! 2. ```sh
//!    CS_EVIDENCE_DIR=private/evidence/T351 \
//!    CS_CANDIDATE_TREE=$(git rev-parse 'HEAD^{tree}') \
//!    CS_EVIDENCE_ARGV="cargo test --workspace --locked -- accept_t351_ --include-ignored" \
//!    CS_EVIDENCE_EXIT_CODE=<status from step 1> \
//!      cargo test --locked --test campaign evidence_report_t351 -- --ignored
//!    ```
//! 3. ```sh
//!    python3 tools/validate_evidence.py private/evidence/T351/acceptance.json \
//!      --artifact-root private/evidence/T351
//!    ```
//!    (no `--require-pass`: the nine recorded unknowns must stay recorded.)
//! 4. Commit a copy of `acceptance.json` as `docs/findings/evidence/T351.json`.

use super::*;

/// The container the member read takes, as the installation spells it.
const CRIMSON_ROF: &str = "GOSDATA/ASSETS/crimson.rof";

/// The `accept_t351_` tests, in the full spelling their original report
/// recorded, each with the evidence entries that row cites. Two of them share
/// a leaf name (`accept_t351_field_value_drops_surrounding_blanks`), which is
/// why the table is keyed by the full id the log prints. Statuses come from
/// the recorded log.
const ASSERTIONS: &[(&str, &[&str])] = &[
    (
        "config::tests::accept_t351_field_value_drops_surrounding_blanks",
        &[
            "cargo-test.log",
            "R4 through cs_content::config::RawField::value and TuningSchema::tune",
        ],
    ),
    (
        "config::tests::accept_t351_lookup_resolves_names_without_regard_to_case",
        &[
            "cargo-test.log",
            "R1 through cs_content::config::ConfigDocument::lookup",
        ],
    ),
    (
        "text::tests_t351::accept_t351_field_value_drops_surrounding_blanks",
        &[
            "cargo-test.log",
            "R4 on an authored member through cs_formats::text::read_keyed_list",
        ],
    ),
    (
        "text::tests_t351::accept_t351_retail_object_names_resolve_only_case_insensitively",
        &[
            "cargo-test.log",
            "R1-R3 measured on LAYOUT.CSV and the 61 .SCRIPT members through read_keyed_list \
             and read_member",
        ],
    ),
    (
        "text::tests_t351::accept_t351_retail_padded_fields_name_defined_resource_ids",
        &[
            "cargo-test.log",
            "R4 measured on SCRAPBOOK.CSV through read_keyed_list and read_resource_header",
        ],
    ),
];

/// The original report's `review.method`, byte for byte. The regeneration
/// facts are appended to it, never substituted for it.
const ORIGINAL_METHOD: &str = "Generated by private/evidence/T351/harness.py on the tested tree from two real runs, nothing written by hand: the task's own selection `cargo test --workspace --locked -- accept_t351_ --include-ignored` (5 tests, 5 passed, 0 failed, 0 ignored, logged to cargo-test.log) and the production `cs-inspect rof` report of GOSDATA/ASSETS/crimson.rof (rof-read-layout.json), whose per-member decoded digests the harness re-derives `content_sha256` from: 65 members (2 keyed field list, 61 .SCRIPT, 2 resource-id headers), digests only, no original bytes. install_sha256 is the production installation fingerprint and equals the value the F02-D and F05-D reports recorded. All three retail-capability tests ran because the selection passes --include-ignored; the harness refuses to write a report if any of the five expected test names is missing from the log or if any is left ignored, and it fails rather than passes when the suite fails. The reviewer re-derived every number in the two retail tables of the findings from the decoded members independently of the suite (34 sections and 0 exact, 12 indented headers = 10 tabs + 2 four-spaces, 1283 entries, 171 comments, 0 semicolons in values, 1 no-separator line at LAYOUT.CSV line 101, 461 scrapbook entries and 461 quoted fields, 7 padded fields each a .H #define, 1313 placeholder references in 113 names, 186 V/G definitions of which 29 global, 0 case-insensitive duplicate keys within a section) and found them all correct. The reviewer also fixed the one defect it found: the retail test's section-name exact-match compared the reader's section name against a bracket-wrapped spelling, so 'no name matches exactly' held vacuously; it now discriminates (a mutation that always matches reports 34 against 0). This report deliberately does NOT use `validate_evidence.py --require-pass`: the task's acceptance criterion is that unestablished rules stay recorded unknowns, and its nine recorded unknowns are listed in `unknowns` above rather than removed to satisfy that flag. The claim stays `implemented`: a merged task is `checked`, never `verified_original`, and nothing here observes the original game running. `human_play` was not available and the nine unknowns that need it stay open.";

/// What this reissue adds to `review.method`: what changed, the correction of
/// the stored-versus-decoded sentence above, and which artifact reproduces.
const REGENERATION: &str = "Regeneration for Rally #1174 (EVIDENCE-CONTENT-DIGEST-OUTLIERS-REPAIR) on 2026-10-10 by bunny-2/bunny-2: the report was reissued by the committed harness crates/cs_app/tests/campaign/evidence/t351.rs, run through the four-step sequence in its module doc, because the sentence above recorded a task-scoped digest in source.content_sha256 — a field whose contract meaning is the canonical whole-installation content fingerprint. source.content_sha256 is now cs_assets::install::content_fingerprint over the manifest production discovery reads (a0223506e512b50c0e0445ba73204a0461e60197e28d58a7f7144632d262c12d), the value every other committed report carries. Correction to the sentence above: the scoped value it describes (e1f7274c663055d3c83fe1401e63d51e493ef51fcd6d3d2d4468dfb2ffdc488f) was computed over the 65 members' stored extent digests, not their per-member decoded digests as that sentence says — all 65 members are compressed, so stored and decoded differ for every one, and the decoded spelling hashes to fa0663c5 instead. The stored-digest computation still re-derives from the same installation bytes through production code in accept_evidence_content_digest_outliers_each_documented_scoped_digest_still_re_derives, and docs/findings/2026-10-10-evidence-content-digest-outliers.md holds the measurement. review.identity above is byte-unchanged: the implementer and reviewer facts stand exactly as the original review wrote them, and this regeneration is recorded here instead of in the identity (#804 convention). Run facts are this run's own: candidate_tree, created_at, command.cwd, the test counts, the assertion statuses and the artifact digests come from the sequence above rather than being carried over. rof-read-layout.json is the production cs-inspect rof member read of ASSETS/LAYOUT.CSV, produced by this harness with the production cs-inspect binary itself, and it reproduces the original report's artifact byte for byte (d64f5b2320783966cce600ba13e5aef407ee2fac92a704baf351eca74ae959f4); cargo-test.log is step 1's log. The nine unknowns above stay open and unchanged, so this report is validated without --require-pass, as the method above says. The claim stays implemented: a merge awards checked, never verified_original, and nothing here observes the original game running; `human_play` was not available and the nine unknowns that need it stay open. `candidate_tree` is the tree of the commit the suite and this harness ran on; the only later delta is this report's own copy under docs/findings/evidence/, which the sentinel tests read only for its source fingerprints.";

/// The nine unknowns the original report recorded, unchanged: each names the
/// affected content, and this task does not close any of them.
const UNKNOWNS: [&str; 9] = [
    "Whether a ';' after a value starts a comment (never observed in 1283 entries).",
    "Escaped or embedded quotes (461 quoted fields, none containing a quote).",
    "Whether a blank byte inside quotes is part of the value.",
    "What the original does with the one LAYOUT.CSV line that has no '=': skip, warn or count, and whether ':' is a second comment marker.",
    "Whether the original folds case over bytes above 0x7F (a localized code page is unmeasured).",
    "Whether a blank at the start of a value is part of the value (never observed).",
    "Case and local-versus-global precedence of <NAME> placeholder references.",
    "Whether the '@' around a section name is part of the name (34 of 35 sections are wrapped).",
    "What the section nesting the indentation shows means, and whether a sub-section is looked up by bare name or by path.",
];

/// The original review's identity, byte for byte: the regeneration must never
/// rewrite who implemented or reviewed this report.
fn review_identity() -> String {
    "bunny-1/bunny-1, the Rally reviewing agent for #351, on the tree it rebased and pushed; the implementer was bunny-1/bunny-1 as well (claim count 2), and this review was a fresh-context pass over the rebased branch, not a re-derivation of the implementer's own work.".to_owned()
}

/// Evidence-report harness for task T351 (Rally #351), reissued under #1174.
/// It refuses every missing input: a report written from a partial sequence
/// would be worse than no report at all.
#[test]
#[ignore = "evidence harness: needs CS_EVIDENCE_DIR, CS_CANDIDATE_TREE, CS_EVIDENCE_ARGV, CS_EVIDENCE_EXIT_CODE, CS_GAME_DIR"]
fn evidence_report_t351_writes_the_acceptance_report() {
    let evidence_dir = workspace_path(&env_var("CS_EVIDENCE_DIR"));
    fs::create_dir_all(&evidence_dir)
        .unwrap_or_else(|error| panic!("create {}: {error}", evidence_dir.display()));
    let candidate_tree = env_var("CS_CANDIDATE_TREE");
    let argv: Vec<String> = env_var("CS_EVIDENCE_ARGV")
        .split_whitespace()
        .map(str::to_owned)
        .collect();
    assert!(
        argv.iter().any(|arg| arg == "accept_t351_"),
        "CS_EVIDENCE_ARGV must be T351's own acceptance selection, got {argv:?}"
    );
    let exit_code: i32 = env_var("CS_EVIDENCE_EXIT_CODE")
        .parse()
        .expect("CS_EVIDENCE_EXIT_CODE must be the exit status of the acceptance run");
    let game_dir = PathBuf::from(env_var("CS_GAME_DIR"));

    let head_tree = git(&["rev-parse", "HEAD^{tree}"]);
    assert_eq!(
        candidate_tree, head_tree,
        "CS_CANDIDATE_TREE must be `git rev-parse 'HEAD^{{tree}}'` of the tested commit; \
         old reports cannot be reused for new code"
    );

    let log_path = evidence_dir.join("cargo-test.log");
    let log = fs::read_to_string(&log_path).unwrap_or_else(|error| {
        panic!(
            "cannot read the acceptance log {}: {error} (step 1 must tee its output there)",
            log_path.display()
        )
    });
    let suite = parse_t351_suite(&log);
    assert_eq!(
        suite.assertions.len() + 1,
        ASSERTIONS.len(),
        "the log holds {} distinct accept_t351_ leaf names and the report records {} rows \
         (two rows share a leaf): {:?}",
        suite.assertions.len(),
        ASSERTIONS.len(),
        suite.assertions
    );

    let found = discover(&game_dir)
        .expect("production discovery must read the original installation for the evidence record");
    let install_sha256 = fingerprint(&found.manifest).to_hex();
    let content_sha256 = content_fingerprint(&found.manifest).to_hex();

    // The production `cs-inspect rof --member` report of LAYOUT.CSV.
    run_rof_read(
        &game_dir,
        "ASSETS/LAYOUT.CSV",
        &evidence_dir.join("rof-read-layout.json"),
    );

    let artifacts = vec![
        artifact(&log_path, "log", &evidence_dir),
        artifact(
            &evidence_dir.join("rof-read-layout.json"),
            "json",
            &evidence_dir,
        ),
    ];

    let engine = Engine {
        rust: rustc_version(),
        bevy: locked_version("bevy"),
        avian: locked_version("avian3d"),
    };
    let unknowns: Vec<String> = UNKNOWNS
        .iter()
        .map(|unknown| (*unknown).to_owned())
        .collect();

    let method = format!("{ORIGINAL_METHOD} {REGENERATION}");
    let report = format!(
        "{{\n\
         \x20\"schema_version\": 1,\n\
         \x20\"task_id\": \"T351\",\n\
         \x20\"candidate_tree\": {},\n\
         \x20\"engine\": {},\n\
         \x20\"created_at\": {},\n\
         \x20\"command\": {{\"argv\": {}, \"cwd\": {}, \"exit_code\": {}}},\n\
         \x20\"source\": {{\"install_sha256\": {}, \"content_sha256\": {}}},\n\
         \x20\"seed\": 0,\n\
         \x20\"ticks\": {{\"start\": 0, \"end\": 0}},\n\
         \x20\"overrides\": [],\n\
         \x20\"capabilities\": [\"retail\", \"synthetic\"],\n\
         \x20\"tests\": {{\"discovered\": {}, \"executed\": {}, \"passed\": {}, \"failed\": {}, \"ignored\": {}}},\n\
         \x20\"assertions\": [{}],\n\
         \x20\"artifacts\": [{}],\n\
         \x20\"unknowns\": {},\n\
         \x20\"review\": {{\"identity\": {}, \"method\": {}}},\n\
         \x20\"claim\": \"implemented\"\n\
         }}\n",
        jstr(&candidate_tree),
        engine_json(&engine),
        jstr(&iso_utc_now()),
        str_array(&argv),
        jstr(&git(&["rev-parse", "--show-toplevel"])),
        exit_code,
        jstr(&install_sha256),
        jstr(&content_sha256),
        suite.discovered,
        suite.executed,
        suite.passed,
        suite.failed,
        suite.ignored,
        tabled_assertions(&log, ASSERTIONS),
        artifact_array(&artifacts),
        str_array(&unknowns),
        jstr(&review_identity()),
        jstr(&method),
    );

    let out = evidence_dir.join("acceptance.json");
    fs::write(&out, &report).unwrap_or_else(|error| panic!("write {}: {error}", out.display()));

    let written = fs::read_to_string(&out).expect("the report reads back");
    let content_line = format!("\"content_sha256\": \"{content_sha256}\"");
    for needle in [
        "\"schema_version\": 1",
        "\"task_id\": \"T351\"",
        "\"claim\": \"implemented\"",
        content_line.as_str(),
        "\"unknowns\": [",
        "\"artifacts\": [",
    ] {
        assert!(
            written.contains(needle),
            "the written report is missing {needle:?}:\n{written}"
        );
    }
    assert!(
        suite.failed == 0 && exit_code == 0,
        "the acceptance run failed (exit {exit_code}, {} failed): the report was written \
         honestly and must NOT validate; fix the tests first",
        suite.failed
    );
    println!("wrote {}", out.display());
}

/// [`parse_suite_prefixed`] with T351's own test prefix.
fn parse_t351_suite(log: &str) -> Suite {
    parse_suite_prefixed(log, "accept_t351_")
}

/// One `cs-inspect rof --member` run: the production command's own bytes,
/// one process per report, so the digest is what a standalone run writes.
fn run_rof_read(game_dir: &Path, member: &str, out: &Path) {
    let cs_path = game_dir.display().to_string();
    let out_path = out.display().to_string();
    let args = [
        "rof",
        "--cs-path",
        cs_path.as_str(),
        "--container",
        CRIMSON_ROF,
        "--member",
        member,
        "--out",
        out_path.as_str(),
    ];
    run_cs_inspect(
        &cs_inspect_binary(),
        &args,
        out,
        &format!("rof --member {member}"),
    );
}
