//! Body creation, its collision bindings and its control-mode transitions
//! (F23-B).
//!
//! Spec: `specs/F23-avian-integration-collision-and-fixed-step-authority.md`,
//! stage `### F23-B`, non-negotiable behaviors 1, 2, 3 and 4.
//!
//! Every value here is authored fixture data: synthetic masses, extents and
//! positions. No original data and no `CS_GAME_DIR` access.

use avian3d::prelude::{
    CollisionEventsEnabled, CollisionLayers as AvianCollisionLayers, LinearVelocity, Mass,
    Position, RigidBody, Sensor, SpeculativeMargin, SweptCcd,
};
use bevy::prelude::Entity;
use cs_app::physics::{
    BodyError, BodyLayer, BodyMode, BodySpec, BodyTransitionError, PhysicsFixture, set_body_mode,
    spawn_body,
};
use cs_sim::collision::{CollisionLayer, ShapeClass};

use crate::common;

/// One body per declared layer, created through the production path.
///
/// Observable failure if the layer binding is dropped or restated wrongly: the
/// entity's Avian membership/filter pair no longer agrees with the declared
/// matrix, or a body that needs a sweep (projectile, trigger) or a bounded
/// speculative margin loses one of them, or a layer that reports contacts
/// loses `CollisionEventsEnabled`.
#[test]
fn accept_f23_b_body_creation_binds_layer_shape_sweep_and_events() {
    let mut fixture = common::fixture(1.0);

    for layer in CollisionLayer::ALL {
        let spec = BodySpec::dynamic_box(layer, 7.0, [0.5, 0.5, 0.5], [1.0, 2.0, 3.0]);
        let entity = spawn_body(fixture.world_mut(), &spec).expect("the spec is valid");
        let body = fixture.world().entity(entity);

        assert_eq!(
            body.get::<BodyLayer>(),
            Some(&BodyLayer(layer)),
            "the contact reporter keys off the declared layer"
        );
        assert_eq!(
            body.get::<RigidBody>(),
            Some(&RigidBody::Dynamic),
            "{layer} must be simulated as declared"
        );
        assert_eq!(
            body.get::<Mass>(),
            Some(&Mass(7.0)),
            "a dynamic body carries the explicit mass, never the autogenerated one"
        );

        let groups = body
            .get::<AvianCollisionLayers>()
            .expect("a spawned body always carries collision groups");
        assert_eq!(
            groups.memberships.0,
            u32::from(layer.bit()),
            "{layer} must be a member of exactly its own bit"
        );
        assert_eq!(
            groups.filters.0,
            u32::from(layer.designed_partners().bits()),
            "{layer} must filter by the designed matrix row"
        );
        for other in CollisionLayer::ALL {
            let other_groups = AvianCollisionLayers::from_bits(
                u32::from(other.bit()),
                u32::from(other.designed_partners().bits()),
            );
            assert_eq!(
                groups.interacts_with(other_groups),
                layer.designed_collides_with(other),
                "the engine filter must equal the declared matrix for {layer} vs {other}"
            );
        }

        assert_eq!(
            body.contains::<SweptCcd>(),
            layer.requires_continuous_detection(),
            "fast layers must opt into the sweep, slow layers must not pay for it"
        );
        let margin = body.get::<SpeculativeMargin>();
        if layer.requires_continuous_detection() {
            assert_eq!(
                margin.map(|margin| margin.0),
                Some(0.0),
                "a swept body must keep a tight speculative margin instead of an inflated hitbox"
            );
        } else {
            assert!(
                margin.is_none(),
                "{layer} must keep the default speculative margin"
            );
        }

        assert_eq!(
            body.contains::<CollisionEventsEnabled>(),
            layer.emits_contact_reports(),
            "the reporting layers must be the ones that emit collision events"
        );
        assert!(
            !body.contains::<Sensor>(),
            "a solid spec must not become a sensor"
        );
    }
}

/// A sensor spec becomes a sensor collider; a solid spec does not.
///
/// Observable failure if `ShapeClass` is ignored: the trigger would resolve as
/// a solid obstacle, or the wall would stop reporting overlaps.
#[test]
fn accept_f23_b_shape_class_binds_to_the_sensor_component() {
    let mut fixture = common::fixture(1.0);

    let mut sensor =
        BodySpec::dynamic_box(CollisionLayer::Trigger, 1.0, [1.0, 1.0, 0.01], [0.0; 3]);
    sensor.shape = ShapeClass::Sensor;
    let sensor_entity = spawn_body(fixture.world_mut(), &sensor).expect("the spec is valid");
    assert!(
        fixture.world().entity(sensor_entity).contains::<Sensor>(),
        "a sensor shape must spawn as a sensor collider"
    );

    let solid_entity = spawn_body(
        fixture.world_mut(),
        &BodySpec::dynamic_box(CollisionLayer::Trigger, 1.0, [1.0, 1.0, 0.01], [0.0; 3]),
    )
    .expect("the spec is valid");
    assert!(
        !fixture.world().entity(solid_entity).contains::<Sensor>(),
        "a solid shape must not become a sensor"
    );
}

/// Invalid specs are rejected at the boundary and spawn nothing.
///
/// Observable failure if a corrupt spec reaches the world: the wrong error is
/// returned, or an entity exists after a rejected request.
#[test]
fn accept_f23_b_body_creation_rejects_invalid_specs() {
    let mut fixture = common::fixture(1.0);
    let before = fixture.world().entities().len();

    let valid = BodySpec::dynamic_box(CollisionLayer::Aircraft, 100.0, [1.0, 0.5, 1.0], [0.0; 3]);

    let mut nan_position = valid;
    nan_position.position_m[1] = f32::NAN;
    assert_eq!(
        spawn_body(fixture.world_mut(), &nan_position),
        Err(BodyError::NonFinite {
            field: "position_m[1]"
        })
    );

    let mut infinite_velocity = valid;
    infinite_velocity.linear_velocity_m_s[2] = f32::INFINITY;
    assert_eq!(
        spawn_body(fixture.world_mut(), &infinite_velocity),
        Err(BodyError::NonFinite {
            field: "linear_velocity_m_s[2]"
        })
    );

    let mut flat_extent = valid;
    flat_extent.half_extents_m[0] = 0.0;
    assert_eq!(
        spawn_body(fixture.world_mut(), &flat_extent),
        Err(BodyError::NonPositiveHalfExtent { axis: "x" })
    );

    let mut massless = valid;
    massless.mass_kg = -3.0;
    assert_eq!(
        spawn_body(fixture.world_mut(), &massless),
        Err(BodyError::NonPositiveMass)
    );

    assert_eq!(
        fixture.world().entities().len(),
        before,
        "a rejected spec must not leave half a body behind"
    );

    // Mass is only meaningful for a body forces can accelerate.
    let mut kinematic = valid;
    kinematic.mode = BodyMode::Kinematic;
    kinematic.mass_kg = 0.0;
    assert!(
        spawn_body(fixture.world_mut(), &kinematic).is_ok(),
        "an unused mass field must not block a kinematic body: {kinematic:?}"
    );
}

/// Kinematic ↔ dynamic transitions change only the control mode.
///
/// Observable failure if a transition rewrites pose or velocity (a release
/// would teleport the aircraft or zero its speed) or if it does not actually
/// switch modes (the body keeps ignoring forces, or keeps integrating while
/// scripted).
#[test]
fn accept_f23_b_control_mode_transition_preserves_pose_and_velocity() {
    let mass_kg = 8.0_f32;
    let force_n = [0.0, 0.0, 24.0];
    let mut fixture = common::empty_fixture();
    let body = common::spawn(
        &mut fixture,
        &BodySpec {
            layer: CollisionLayer::Aircraft,
            shape: ShapeClass::Solid,
            mode: BodyMode::Dynamic,
            mass_kg,
            half_extents_m: [0.5, 0.5, 0.5],
            position_m: [0.0, 0.0, 0.0],
            linear_velocity_m_s: [6.0, 0.0, 0.0],
        },
    );
    fixture.step(1);

    let released = sample(&fixture, body);
    assert_eq!(
        set_body_mode(fixture.world_mut(), body, BodyMode::Kinematic),
        Ok(BodyMode::Kinematic)
    );
    let kinematic = sample(&fixture, body);
    assert_eq!(
        kinematic, released,
        "entering scripted mode must not touch pose or velocity"
    );

    fixture.step(1);
    let scripted = sample(&fixture, body);
    assert_eq!(
        scripted.velocity, released.velocity,
        "kinematic mode must keep the trajectory velocity"
    );
    assert!(
        scripted.position[0] > released.position[0],
        "kinematic mode must still advance along the trajectory: {scripted:?}"
    );

    assert_eq!(
        set_body_mode(fixture.world_mut(), body, BodyMode::Dynamic),
        Ok(BodyMode::Dynamic)
    );
    let back_to_dynamic = sample(&fixture, body);
    assert_eq!(
        back_to_dynamic, scripted,
        "releasing the body must not teleport it or reset its velocity"
    );

    let dt = fixture.timestep_s();
    fixture.submit(common::force_request(body, force_n));
    fixture.step(1);
    let forced = sample(&fixture, body);
    let expected = force_n[2] / mass_kg * dt;
    assert!(
        (forced.velocity[2] - expected).abs() <= 1e-4 * expected.max(1.0),
        "the released body must take the force as a dynamic body: expected {expected}, got {:?}",
        forced.velocity
    );

    // A mode change to the mode already in effect is a no-op, and a body that
    // does not exist cannot transition.
    assert_eq!(
        set_body_mode(fixture.world_mut(), body, BodyMode::Dynamic),
        Ok(BodyMode::Dynamic)
    );
    let stale = Entity::PLACEHOLDER;
    assert_eq!(
        set_body_mode(fixture.world_mut(), stale, BodyMode::Static),
        Err(BodyTransitionError::NotABody)
    );
}

/// Pose and velocity of one specific body (the fixture's own spare body is
/// parked far away and must not be measured by accident).
#[derive(Clone, Copy, Debug, PartialEq)]
struct Sample {
    position: [f32; 3],
    velocity: [f32; 3],
}

fn sample(fixture: &PhysicsFixture, entity: Entity) -> Sample {
    let body = fixture.world().entity(entity);
    Sample {
        position: body
            .get::<Position>()
            .expect("the body has a position")
            .0
            .to_array(),
        velocity: body
            .get::<LinearVelocity>()
            .expect("the body has a velocity")
            .0
            .to_array(),
    }
}
