//! Body creation, collision binding, sweeps and control-mode transitions
//! (F23-B).
//!
//! Spec: `specs/F23-avian-integration-collision-and-fixed-step-authority.md`,
//! stage `### F23-B`. Shared contract: `docs/contracts/FLIGHT-PHYSICS.md`.
//!
//! [`spawn_body`] is the one place a runtime body enters the physics world:
//! it validates a [`BodySpec`] at the boundary and turns the engine-neutral
//! vocabulary of `cs_sim::collision` into real Avian components, so no other
//! code has to remember which layer needs which binding:
//!
//! * the declared [`CollisionLayer`] becomes the entity's [`BodyLayer`] marker
//!   (the key the contact reporter classifies with) **and** an Avian
//!   [`CollisionLayers`] membership/filter pair built from
//!   [`CollisionLayer::designed_partners`], so the engine's broad phase
//!   filters by the declared matrix rather than by a restated copy of it;
//! * [`ShapeClass::Sensor`] becomes Avian's [`Sensor`], which keeps a
//!   trigger a reported overlap instead of a solid obstacle;
//! * layers that [`requires_continuous_detection`](CollisionLayer::requires_continuous_detection)
//!   (fast projectiles and narrow triggers) get [`SweptCcd`] *and* a zero
//!   [`SpeculativeMargin`]. The sweep is the tunneling fix; bounding the
//!   speculative margin is what keeps that fix from inflating the body's
//!   effective hitbox — with the default unbounded margin a fast body predicts
//!   contacts metres ahead of itself, which is exactly the "globally inflated
//!   hitbox" non-negotiable behavior 3 forbids;
//! * [`CollisionEventsEnabled`] is added for the layers that
//!   [`emits_contact_reports`](CollisionLayer::emits_contact_reports);
//! * a dynamic body carries an explicit [`Mass`], never the collider's
//!   autogenerated one (non-negotiable behavior 4).
//!
//! [`set_body_mode`] swaps a live body between the dynamic, kinematic and
//! static modes without writing pose or velocity, which is the controlled
//! transition non-negotiable behavior 1 asks for: a scripted actor runs
//! kinematic until it is released, and release must not teleport it or reset
//! its velocity.
//!
//! **Designed bindings, not original data.** Every binding here follows the
//! spec's declared behavior and Avian 0.7's measured API; which layers,
//! sweeps and mass rules the original 2000 PC game used is **unknown** until
//! F23-D measures it. See
//! `docs/findings/2026-09-30-f23-b-body-creation-forces-sweeps-and-transitions.md`.

use std::fmt;

use avian3d::prelude::{
    AngularVelocity, Collider, CollisionEventsEnabled, CollisionLayers as AvianCollisionLayers,
    LinearVelocity, Mass, Position, RigidBody, Rotation, Sensor, Sleeping, SpeculativeMargin,
    SweptCcd, TransformInterpolation,
};
use bevy::prelude::{Component, Entity, Transform, Vec3, World};
use cs_sim::collision::{CollisionLayer, ShapeClass};

/// How a body is simulated.
///
/// The three modes map one-to-one onto Avian's [`RigidBody`] kinds; the type
/// exists so gameplay can speak about control ownership
/// (`docs/contracts/FLIGHT-PHYSICS.md`) without naming engine variants.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum BodyMode {
    /// Forces, contacts and the integrator own the pose: aircraft in flight.
    Dynamic,
    /// Nothing moves the body except its own velocity, which gameplay writes:
    /// scripted/trajectory actors (non-negotiable behavior 1).
    Kinematic,
    /// Immovable world geometry.
    Static,
}

impl BodyMode {
    /// Whether the body is integrated from velocity (dynamic or kinematic).
    pub const fn is_simulated(self) -> bool {
        !matches!(self, Self::Static)
    }
}

impl From<BodyMode> for RigidBody {
    fn from(mode: BodyMode) -> Self {
        match mode {
            BodyMode::Dynamic => Self::Dynamic,
            BodyMode::Kinematic => Self::Kinematic,
            BodyMode::Static => Self::Static,
        }
    }
}

/// The declared identity of a body before it exists.
///
/// Construct and pass to [`spawn_body`]; every field is validated there
/// (non-finite input is rejected at the boundary, contract: "Reject nonfinite
/// inputs at boundaries").
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct BodySpec {
    /// Which declared collision layer the body belongs to.
    pub layer: CollisionLayer,
    /// Solid obstacle or sensor volume.
    pub shape: ShapeClass,
    /// How the body is simulated.
    pub mode: BodyMode,
    /// Total mass in kilograms. Required to be positive for
    /// [`BodyMode::Dynamic`]; a static or kinematic body is not accelerated
    /// by forces, so the field is validated as finite but not required.
    /// When a non-dynamic spec does carry a positive mass it is still bound
    /// to the body, so a later [`set_body_mode`] release to
    /// [`BodyMode::Dynamic`] integrates with the declared mass rather than
    /// a collider-density default — a kinematic spec that means to be
    /// released should declare its mass.
    pub mass_kg: f32,
    /// Half of each collider dimension in meters. Strictly positive.
    pub half_extents_m: [f32; 3],
    /// Initial world position in meters.
    pub position_m: [f32; 3],
    /// Initial world velocity in m/s.
    pub linear_velocity_m_s: [f32; 3],
}

const SPEC_SCALAR_FIELDS: [&str; 10] = [
    "mass_kg",
    "half_extents_m[0]",
    "half_extents_m[1]",
    "half_extents_m[2]",
    "position_m[0]",
    "position_m[1]",
    "position_m[2]",
    "linear_velocity_m_s[0]",
    "linear_velocity_m_s[1]",
    "linear_velocity_m_s[2]",
];

impl BodySpec {
    /// A dynamic box of `mass_kg` on `layer` at `position_m`, at rest.
    pub const fn dynamic_box(
        layer: CollisionLayer,
        mass_kg: f32,
        half_extents_m: [f32; 3],
        position_m: [f32; 3],
    ) -> Self {
        Self {
            layer,
            shape: ShapeClass::Solid,
            mode: BodyMode::Dynamic,
            mass_kg,
            half_extents_m,
            position_m,
            linear_velocity_m_s: [0.0, 0.0, 0.0],
        }
    }

    /// Validates every scalar of the spec.
    pub fn validate(&self) -> Result<(), BodyError> {
        for (field, value) in SPEC_SCALAR_FIELDS.into_iter().zip([
            self.mass_kg,
            self.half_extents_m[0],
            self.half_extents_m[1],
            self.half_extents_m[2],
            self.position_m[0],
            self.position_m[1],
            self.position_m[2],
            self.linear_velocity_m_s[0],
            self.linear_velocity_m_s[1],
            self.linear_velocity_m_s[2],
        ]) {
            if !value.is_finite() {
                return Err(BodyError::NonFinite { field });
            }
        }
        for (axis, extent) in ["x", "y", "z"].into_iter().zip(self.half_extents_m) {
            if extent <= 0.0 {
                return Err(BodyError::NonPositiveHalfExtent { axis });
            }
        }
        if self.mode == BodyMode::Dynamic && self.mass_kg <= 0.0 {
            return Err(BodyError::NonPositiveMass);
        }
        Ok(())
    }
}

/// Why a [`BodySpec`] could not enter the world.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum BodyError {
    /// A named scalar field was NaN or infinite.
    NonFinite { field: &'static str },
    /// A box half extent was not strictly positive.
    NonPositiveHalfExtent { axis: &'static str },
    /// A dynamic body's mass was not strictly positive.
    NonPositiveMass,
}

impl fmt::Display for BodyError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NonFinite { field } => write!(f, "{field} must be finite"),
            Self::NonPositiveHalfExtent { axis } => {
                write!(f, "half_extents_m[{axis}] must be greater than zero")
            }
            Self::NonPositiveMass => f.write_str("mass_kg must be greater than zero"),
        }
    }
}

impl std::error::Error for BodyError {}

/// The declared collision layer of a spawned body.
///
/// The contact reporter reads this marker to classify an Avian collision
/// event with `cs_sim::collision::classify_contact`, so the sensor/solid
/// decision is made by the shared vocabulary, not by the engine.
#[derive(Component, Clone, Copy, Debug, PartialEq, Eq)]
pub struct BodyLayer(pub CollisionLayer);

/// Spawns one body from `spec`, binding every declared property to Avian.
///
/// Returns the new entity, or the first violated field of the spec — nothing
/// is spawned when validation fails, so a rejected request never leaves half a
/// body behind.
pub fn spawn_body(world: &mut World, spec: &BodySpec) -> Result<Entity, BodyError> {
    spec.validate()?;

    let layer = spec.layer;
    let half = spec.half_extents_m;
    let position = Vec3::from_array(spec.position_m);

    // Everything except the collider first: Avian creates the broad-phase
    // proxy (and samples the sensor/event flags) when the collider appears, so
    // those flags have to exist by then or the body's contacts silently never
    // reach the event stream.
    let mut entity = world.spawn((
        RigidBody::from(spec.mode),
        Transform::from_translation(position),
        Position(position),
        Rotation::default(),
        LinearVelocity(Vec3::from_array(spec.linear_velocity_m_s)),
        AngularVelocity(Vec3::ZERO),
        BodyLayer(layer),
        AvianCollisionLayers::from_bits(
            u32::from(layer.bit()),
            u32::from(layer.designed_partners().bits()),
        ),
    ));

    if spec.shape.is_sensor() {
        entity.insert(Sensor);
    }
    if layer.emits_contact_reports() {
        entity.insert(CollisionEventsEnabled);
    }
    if layer.requires_continuous_detection() {
        entity.insert((SweptCcd::default(), SpeculativeMargin::ZERO));
    }
    if spec.mode.is_simulated() {
        // Presentation eases the render transform between fixed ticks
        // (F23-C): an integrated body interpolates, a static one never moves
        // and has nothing to ease.
        entity.insert(TransformInterpolation);
    }

    if spec.mass_kg > 0.0 {
        // Avian recomputes `ComputedMass` when the collider arrives, so the
        // explicit mass must already be on the entity or the body's first
        // tick integrates with the default unit mass (measured through the
        // F23-C session path: a force on a spawned 20 kg body accelerated
        // it like a 1 kg one). The declared mass is bound for every mode —
        // not only dynamic — so a kinematic release keeps it.
        entity.insert(Mass(spec.mass_kg));
    }

    entity.insert(Collider::cuboid(
        half[0] * 2.0,
        half[1] * 2.0,
        half[2] * 2.0,
    ));

    Ok(entity.id())
}

/// A mode transition that cannot be honoured.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum BodyTransitionError {
    /// The entity does not exist or carries no [`RigidBody`].
    NotABody,
    /// The transition is to [`BodyMode::Dynamic`] but the entity carries no
    /// declared [`Mass`]: releasing a body to the integrator without one
    /// would silently integrate the collider-density default
    /// (non-negotiable behavior 4), so the transition is refused.
    MissingDynamicMass,
}

impl fmt::Display for BodyTransitionError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NotABody => f.write_str("entity is not a rigid body"),
            Self::MissingDynamicMass => {
                f.write_str("a dynamic release needs a declared mass; the body carries none")
            }
        }
    }
}

impl std::error::Error for BodyTransitionError {}

/// Switches a live body to `mode`, preserving pose and velocity.
///
/// The transition writes nothing dynamic but the [`RigidBody`] kind, clears
/// sleep and keeps [`TransformInterpolation`] in step with whether the body
/// is integrated: `Position`, `Rotation`, `LinearVelocity` and
/// `AngularVelocity` are left exactly as they are, so a kinematic → dynamic
/// release continues from the pose and velocity the scripted trajectory
/// had, with no discontinuity (spec non-negotiable behavior 1; the
/// end-to-end AC03 scenario is F23-C's).
///
/// Returns the mode that was already in effect when nothing changes.
pub fn set_body_mode(
    world: &mut World,
    entity: Entity,
    mode: BodyMode,
) -> Result<BodyMode, BodyTransitionError> {
    let current = world
        .get::<RigidBody>(entity)
        .copied()
        .ok_or(BodyTransitionError::NotABody)?;

    if current == RigidBody::from(mode) {
        return Ok(mode);
    }

    if mode == BodyMode::Dynamic {
        let mass = world.get::<Mass>(entity).map(|mass| mass.0);
        match mass {
            Some(mass) if mass > 0.0 => {}
            _ => return Err(BodyTransitionError::MissingDynamicMass),
        }
    }

    let mut target = world.entity_mut(entity);
    target.insert(RigidBody::from(mode));
    // A mode change is a deliberate gameplay event: the body must be
    // simulated in its new mode, not left asleep in the old one. Avian's
    // observers rebuild or drop the solver body at the next command flush.
    target.remove::<Sleeping>();
    // Render interpolation tracks whether the body is integrated: a body
    // entering simulation eases its transform, a parked one does not.
    if mode.is_simulated() {
        target.insert(TransformInterpolation);
    } else {
        target.remove::<TransformInterpolation>();
    }
    Ok(mode)
}
